### ISSUE TITLE
SASL To-Do's

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#832]
This is a placeholder issue to track SASL-related implementation items.

- [x] Handle timeouts during connect
- [x] Handle failed SASL auth - connect anyway, or jump to next server?
- [x] Error check key files before authentication
- [ ] Deconflict with pre-init binds
- [x] Handle bots without openssl installed
- [ ] #688 (comment) - grawity proposed replacing sasl state processing with real state keeping.
- [x] Compat/Fallback for resolv.h base64 encode b64_ntop() and base64 decode b64_pton()
- [ ] Implement scram authentication
- [ ] Handle 908 messages

**Comment by michaelortmann** [comment]
scram authentication needs pbkdf2

**Comment by michaelortmann** [comment]
908 isn't handeled by irssi nor weechat.

**Comment by michaelortmann** [comment]
I cant edit the checklist.
#1706 will check some boxes.

New boxes:
- sasl-password should? be sasl-password-file so we read the pass from file and keep it only in memory while we need it
- we could also enable/disable all sasl raw bindings to minimize attack surface
- in the end, fuzzing would be nice, coze we do some parsing here
- support authenticate split by 400 byte, like:
  https://github.com/ircv3/ircv3-specifications/commit/838ef397385065bbc5c29d934bbb407e5b5a5ce5
  400-byte chunk, see: https://ircv3.net/specs/extensions/sasl-3.1.html
  base64 padding
  The response is encoded in Base64 (RFC 4648), then split to 400-byte chunks, and each chunk is sent as a separate AUTHENTICATE command.
